"""Demo student profiles for one-click assessment fill."""

from __future__ import annotations

from backend.app.schemas.schemas import DemoProfile, StudentAssessmentInput

DEMO_PROFILES: list[DemoProfile] = [
    DemoProfile(
        key="top_candidate",
        label="Top Candidate",
        summary="Product-company ready: high CGPA, internships, strong DSA.",
        payload=StudentAssessmentInput(
            name="Aarav Sharma",
            email="aarav.sharma@college.edu",
            gender="Male",
            department="AIML",
            cgpa=8.7,
            tenth_percentage=93,
            twelfth_percentage=91,
            backlogs=0,
            attendance_percentage=94,
            aptitude_score=88,
            coding_score=90,
            communication_score=82,
            technical_score=86,
            dsa_score=88,
            number_of_projects=5,
            number_of_internships=2,
            number_of_certifications=4,
            leetcode_problems=240,
            programming_languages=["Python", "JavaScript", "Java"],
            cloud_skills=["AWS", "Docker"],
            database_skills=["SQL", "PostgreSQL"],
            tools=["Git", "Linux", "REST APIs", "Machine Learning", "CI/CD"],
            target_career="Machine Learning Engineer",
        ),
    ),
    DemoProfile(
        key="average_candidate",
        label="Average Candidate",
        summary="Typical tier-2 profile with mixed scores and one project.",
        payload=StudentAssessmentInput(
            name="Diya Patel",
            email="diya.patel@college.edu",
            gender="Female",
            department="CSE",
            cgpa=7.2,
            tenth_percentage=78,
            twelfth_percentage=74,
            backlogs=1,
            attendance_percentage=82,
            aptitude_score=68,
            coding_score=64,
            communication_score=66,
            technical_score=62,
            dsa_score=58,
            number_of_projects=2,
            number_of_internships=0,
            number_of_certifications=1,
            leetcode_problems=45,
            programming_languages=["Python", "Java"],
            cloud_skills=[],
            database_skills=["SQL"],
            tools=["Git"],
            target_career="Software Engineer",
        ),
    ),
    DemoProfile(
        key="high_risk",
        label="High Risk Profile",
        summary="High backlogs, low coding practice, limited internships.",
        payload=StudentAssessmentInput(
            name="Rohan Verma",
            email="rohan.verma@college.edu",
            gender="Male",
            department="ECE",
            cgpa=6.1,
            tenth_percentage=62,
            twelfth_percentage=58,
            backlogs=4,
            attendance_percentage=68,
            aptitude_score=48,
            coding_score=42,
            communication_score=50,
            technical_score=45,
            dsa_score=38,
            number_of_projects=0,
            number_of_internships=0,
            number_of_certifications=0,
            leetcode_problems=8,
            programming_languages=["C++"],
            cloud_skills=[],
            database_skills=[],
            tools=[],
            target_career=None,
        ),
    ),
]
