export const emptyForm = {
  name: "",
  email: "",
  gender: "Male",
  department: "AIML",
  cgpa: 7.5,
  tenth_percentage: 80,
  twelfth_percentage: 76,
  backlogs: 0,
  attendance_percentage: 85,
  aptitude_score: 70,
  coding_score: 68,
  communication_score: 70,
  technical_score: 68,
  dsa_score: 65,
  number_of_projects: 2,
  number_of_internships: 0,
  number_of_certifications: 1,
  leetcode_problems: 60,
  programming_languages: ["Python"],
  cloud_skills: [],
  database_skills: ["SQL"],
  tools: ["Git"],
  target_career: "",
  question: "",
};

export const presets = {
  top_candidate: {
    name: "Aarav Sharma",
    email: "aarav.sharma@college.edu",
    gender: "Male",
    department: "AIML",
    cgpa: 8.7,
    tenth_percentage: 93,
    twelfth_percentage: 91,
    backlogs: 0,
    attendance_percentage: 94,
    aptitude_score: 88,
    coding_score: 90,
    communication_score: 82,
    technical_score: 86,
    dsa_score: 88,
    number_of_projects: 5,
    number_of_internships: 2,
    number_of_certifications: 4,
    leetcode_problems: 240,
    programming_languages: ["Python", "JavaScript", "Java"],
    cloud_skills: ["AWS", "Docker"],
    database_skills: ["SQL", "PostgreSQL"],
    tools: ["Git", "Linux", "REST APIs", "Machine Learning", "CI/CD"],
    target_career: "Machine Learning Engineer",
    question: "",
  },
  average_candidate: {
    name: "Diya Patel",
    email: "diya.patel@college.edu",
    gender: "Female",
    department: "CSE",
    cgpa: 7.2,
    tenth_percentage: 78,
    twelfth_percentage: 74,
    backlogs: 1,
    attendance_percentage: 82,
    aptitude_score: 68,
    coding_score: 64,
    communication_score: 66,
    technical_score: 62,
    dsa_score: 58,
    number_of_projects: 2,
    number_of_internships: 0,
    number_of_certifications: 1,
    leetcode_problems: 45,
    programming_languages: ["Python", "Java"],
    cloud_skills: [],
    database_skills: ["SQL"],
    tools: ["Git"],
    target_career: "Software Engineer",
    question: "",
  },
  high_risk: {
    name: "Rohan Verma",
    email: "rohan.verma@college.edu",
    gender: "Male",
    department: "ECE",
    cgpa: 6.1,
    tenth_percentage: 62,
    twelfth_percentage: 58,
    backlogs: 4,
    attendance_percentage: 68,
    aptitude_score: 48,
    coding_score: 42,
    communication_score: 50,
    technical_score: 45,
    dsa_score: 38,
    number_of_projects: 0,
    number_of_internships: 0,
    number_of_certifications: 0,
    leetcode_problems: 8,
    programming_languages: ["C++"],
    cloud_skills: [],
    database_skills: [],
    tools: [],
    target_career: "",
    question: "",
  },
};

export const languageOptions = ["Python", "Java", "JavaScript", "TypeScript", "C++", "C#", "Go"];
export const cloudOptions = ["AWS", "Azure", "GCP", "Docker", "Kubernetes"];
export const databaseOptions = ["SQL", "PostgreSQL", "MySQL", "MongoDB"];
export const toolOptions = [
  "Git",
  "Linux",
  "CI/CD",
  "Terraform",
  "React",
  "Node.js",
  "REST APIs",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Data Analysis",
];

export function statusTone(status) {
  if (status === "High" || Number(status) > 70) {
    return { text: "text-emerald-300", bar: "#34d399", bg: "bg-emerald-500/15" };
  }
  if (status === "Medium" || Number(status) >= 40) {
    return { text: "text-amber-300", bar: "#fbbf24", bg: "bg-amber-500/15" };
  }
  return { text: "text-rose-300", bar: "#f43f5e", bg: "bg-rose-500/15" };
}

export const scoreBenchmarks = {
  default: { coding: 75, dsa: 70, aptitude: 70, communication: 72, technical: 74, cgpa: 75 },
  "Machine Learning Engineer": { coding: 82, dsa: 78, aptitude: 76, communication: 70, technical: 84, cgpa: 80 },
  "Software Engineer": { coding: 82, dsa: 80, aptitude: 72, communication: 70, technical: 76, cgpa: 75 },
  "Backend Developer": { coding: 80, dsa: 74, aptitude: 70, communication: 68, technical: 82, cgpa: 74 },
  "Full Stack Developer": { coding: 80, dsa: 70, aptitude: 68, communication: 76, technical: 78, cgpa: 74 },
  "Data Engineer": { coding: 76, dsa: 68, aptitude: 74, communication: 68, technical: 82, cgpa: 76 },
  "DevOps Engineer": { coding: 74, dsa: 62, aptitude: 70, communication: 68, technical: 84, cgpa: 72 },
  "Cloud Engineer": { coding: 72, dsa: 60, aptitude: 70, communication: 68, technical: 84, cgpa: 72 },
};

export function toPayload(form) {
  return {
    ...form,
    cgpa: Number(form.cgpa),
    tenth_percentage: Number(form.tenth_percentage),
    twelfth_percentage: Number(form.twelfth_percentage),
    backlogs: Number(form.backlogs),
    attendance_percentage: Number(form.attendance_percentage),
    aptitude_score: Number(form.aptitude_score),
    coding_score: Number(form.coding_score),
    communication_score: Number(form.communication_score),
    technical_score: Number(form.technical_score),
    dsa_score: Number(form.dsa_score),
    number_of_projects: Number(form.number_of_projects),
    number_of_internships: Number(form.number_of_internships),
    number_of_certifications: Number(form.number_of_certifications),
    leetcode_problems: Number(form.leetcode_problems),
    email: form.email || null,
    name: form.name || null,
    target_career: form.target_career || null,
    question: form.question || null,
  };
}
